### ISSUE TITLE
Example Assist

### ISSUE THREAD

**Issue by bhclowers** [Optivolt-Labs/MPwm#1]
Any chance you could provide a brief example on how to compile and run a simple script where the frequency of the PWM is changed?

**Comment by imbuedHope** [comment]
I haven't tested this since I don't have a dev kit on me, but something like this should work.

```cpp
#include "mpwm.h"

// valid GCLK value depends on which internal clock you want to use
// some of them are used by arduino core or in other libs, it's worth poking around
// arduino core to double check since it sometimes varies from board to board
// personally found GCLK2 to be a safe bet

MPwm::MatchPwm pwm_signal = MPwm::MatchPwm(30, MPwm::GClk::GCLK2);

void setup() {
    pinMode(30, OUTPUT);

    // set pwm to some default value to start with
    pwm_signal.enable();
    pwm_signal.write(.5, 100000); // 50% duty cycle at 100000Hz
}

float max_freq = 150000;
float min_freq = 50000;
float freq_stp = 10000;
bool increase_duty = true;

void loop() {
    if(increase_duty) {
        float freq_target = pwm_signal.getFrequency() + freq_stp;
        if (freq_target > max_freq) {
            increase_duty = false;
        } else {
            pwm_signal.setFrequency(freq_target);
        }
    } else {
        float freq_target = pwm_signal.getFrequency() - freq_stp;
        if (freq_target < min_freq) {
            increase_duty = true;
        } else {
            pwm_signal.setFrequency(freq_target);
        }
    }
}
```

Some notes if you're planning on using this in a project:  
* This lib works by changing the underlying TC module to change the freq, if there's other stuff using the same TC module then it can break things unexpectedly; usually not a problem
* It's setup for the greatest accuracy possible, but the lower the frequency you go the worse the duty cycle accuracy gets due to rounding. Underneath it all a 50% duty pwm at 10kHz is basically count to 5kHz or just past it w/ the provided clock and then toggle the wave form so when we change the frequency to 8kHz it becomes count to 4kHz which is going to be a more inaccurate duty cycle due to lower counting accuracy.
